version: "3.9"
services:
  monetdb:
    image: monetdb/monetdb:Oct2020-SP3
    container_name: projeto_aplicacao_monetdb
    restart: always
    volumes:
      - ./monetdb/data:/var/data
    ports:
      - 50000:50000
  mongodb:
    image: mongo:4.4
    container_name: projeto_aplicacao_mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=tcc
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    ports:
      - 27017:27017
  neo4jdb:
    image: neo4j:4.1
    container_name: projeto_aplicacao_neo4j
    restart: always
    ports:
      - 7687:7687
  postgresdb:
    image: postgres:13.3
    container_name: projeto_aplicacao_postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tcc
    ports:
      - 5432:5432
  cassandradb:
    image: cassandra:4.0
    container_name: projeto_aplicacao_cassandra
    restart: always
    ports:
      - 9042:9042
  redisdb:
    image: redis:6.2
    container_name: projeto_aplicacao_redis
    restart: always
    ports:
      - 6379:6379