version: "3.9"
services:
  monetdb:
    image: monetdb/monetdb:Oct2020-SP3
    container_name: projeto_aplicacao_monetdb
    restart: always
    volumes:
      - ./monetdb/data:/var/data
    working_dir: /var/data
    ports:
      - 50000:50000
  mongodb:
    image: mongo:4.4
    container_name: projeto_aplicacao_mongodb
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=tcc
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root_password
    volumes:
      - ./mongodb/data:/data/db
    ports:
      - 27017:27017
    volumes:
      - ./mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro